package com.manuanand.habitstreak;

import java.util.Date;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/habitstreak") // This means URL's start with /habitstreak (after Application path)
public class HabitController {
	@Autowired // This means to get the bean called habitRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private HabitRepository habitRepository;
	
	///
	// Habit Repository
	///
	@PostMapping(path="/addHabit") // Map ONLY POST Requests
	public @ResponseBody String addHabit (@RequestParam String name, 
			@RequestParam String description, @RequestParam Integer numSessions,
			@RequestParam(required = false) Date startDate, @RequestParam (required = false) Date endDate) {

		Habit newHabit = new Habit();
		newHabit = populateHabit(newHabit, name, description, numSessions, 
				startDate, endDate);
		habitRepository.save(newHabit);
		
		return "Saved";
	}

	@GetMapping(path="/getAllHabits")
	public @ResponseBody Iterable<Habit> getHabits() {
		
		// This returns a JSON or XML with the users
		return habitRepository.findAll();
	}
	
	@GetMapping(path="/getHabitById")
	public @ResponseBody Habit getHabitById(@RequestParam int id) {
		
		Optional<Habit> habit = habitRepository.findById(id);
		if (!habit.isEmpty()) {
			return habit.get();
		} 
		
		return null;
	}
	
	///
	/// Helper Methods
	///
	private Habit populateHabit( Habit newHabit, String name, String description, Integer numSessions, 
			Date startDate, Date endDate)
	{
		newHabit.setName(name);
		newHabit.setDescription(description);
		newHabit.setNumSessions(numSessions);
		
		if (startDate == null) {
			startDate = new Date();
		}
		newHabit.setStartDate(startDate);
		newHabit.setEndDate(endDate);
		
		return newHabit;
	}
}